name: graph_ql_demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.6
  gql: ^1.0.0+1
  graphql_flutter: ^5.1.2
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
